In [21]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
#Importing Libraries

In [22]:
Log_Train = pd.read_csv(r'C:\Users\shres\Desktop\Datasets\EMNIST Train.csv',header=None)
Log_Test = pd.read_csv(r'C:\Users\shres\Desktop\Datasets\EMNIST Test.csv',header=None)
Train = Log_Train.to_numpy()
Test = Log_Test.to_numpy()

In [23]:
Log_Train

,0,1,2,3,4,5,6,7,8,9,...,775,776,777,778,779,780,781,782,783,784
0,23,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,7,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,16,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,15,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,23,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
88795,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
88796,21,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
88797,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
88798,23,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
88799,12,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [24]:
Log_Test

,0,1,2,3,4,5,6,7,8,9,...,775,776,777,778,779,780,781,782,783,784
0,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14795,19,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
14796,19,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
14797,19,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
14798,19,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
14799,19,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [25]:
IM = np.identity(26)
y_class = Train[:,0]
y_list = []
for i in range(Train.shape[0]) :
    a = y_class[i]-1
    y_list.append(IM[a,:])
Y = np.array(y_list)
print(Y,'\n',Y.shape)

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [1. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
 (88800, 26)

In [26]:
X1 = Train[:,1:Train.shape[1]]
print(X1,X1.shape)

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]] (88800, 784)

In [27]:
X = X1/255
X

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [28]:
X_Test1 = Test[:,1:Test.shape[1]]
print(X_Test1,'\n',X_Test1.shape)

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
 (14800, 784)

In [29]:
X_Test = X_Test1/255
X_Test

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [39]:
def logistic_regression(iterations,learning_rate,X,Y,X_Test):
    theta = np.zeros((X.shape[1],26))
    m = X.shape[0]
    for i in range(iterations):
        Z = np.dot(X,theta)
        hyp = 1/(1+np.exp(-Z))
        cost = (np.sum((Y)*np.log(hyp)+(1-Y)*np.log(1-hyp)))*(-1/m)
        grad = np.dot(X.T,(hyp-Y))
        theta = theta - (learning_rate/m) * (grad)
        plt.scatter(i,cost)
    print(cost)
    Y_P1 = np.dot(X_Test,theta)
    Y_Prob = 1/(1+np.exp(-Y_P1))
    return Y_Prob

In [40]:
Y_Prob=logistic_regression(2000,1.2,X,Y,X_Test)

2.0561311357222447

In [41]:
Y_Prob

array([[1.49007774e-01, 6.66158210e-03, 2.48361689e-05, ...,
        3.91497856e-04, 7.92952367e-03, 1.34307564e-07],
       [1.02786470e-01, 2.91389660e-03, 1.01153454e-09, ...,
        2.60642832e-01, 1.02765783e-02, 2.96946205e-04],
       [5.97109411e-01, 2.09725278e-05, 6.35622783e-02, ...,
        2.85065453e-04, 1.51844064e-05, 1.05310873e-03],
       ...,
       [9.73016689e-03, 3.47649700e-02, 4.17978484e-05, ...,
        2.11616775e-05, 1.32290665e-06, 1.17364434e-04],
       [1.70673890e-02, 6.31016331e-02, 5.06829902e-03, ...,
        5.72209110e-03, 3.37655036e-03, 2.43400782e-03],
       [3.46897667e-01, 1.06799226e-03, 3.38926585e-02, ...,
        1.49045767e-02, 1.63950876e-05, 6.20750290e-04]])

In [42]:
Y_Prob.shape

(14800, 26)

In [43]:
Y_Pred2 = np.argmax(Y_Prob,axis=1)
Y_Pred3 = Y_Pred2 + 1
Y_Pred3

array([ 5, 24,  1, ..., 19, 10,  1], dtype=int64)

In [44]:
Y_True = Test[:,0]
Y_True

array([ 1,  1,  1, ..., 19, 19, 19], dtype=int64)

In [45]:
Y33=(Y_Pred3-Y_True).tolist()
Y33

[4,
 23,
 0,
 16,
 0,
 0,
 0,
 0,
 16,
 0,
 13,
 0,
 6,
 0,
 13,
 0,
 11,
 0,
 0,
 16,
 0,
 10,
 4,
 0,
 0,
 0,
 0,
 6,
 0,
 0,
 0,
 0,
 0,
 16,
 13,
 0,
 13,
 7,
 0,
 0,
 0,
 25,
 0,
 0,
 20,
 0,
 0,
 16,
 20,
 0,
 0,
 16,
 3,
 6,
 0,
 0,
 0,
 0,
 0,
 20,
 0,
 0,
 6,
 0,
 0,
 0,
 0,
 0,
 13,
 3,
 0,
 0,
 0,
 6,
 25,
 0,
 6,
 0,
 3,
 0,
 14,
 0,
 0,
 0,
 25,
 0,
 0,
 0,
 20,
 0,
 20,
 13,
 0,
 0,
 25,
 0,
 16,
 0,
 20,
 0,
 0,
 7,
 0,
 5,
 0,
 0,
 6,
 0,
 0,
 0,
 25,
 4,
 3,
 0,
 0,
 0,
 0,
 14,
 0,
 25,
 0,
 14,
 0,
 10,
 0,
 0,
 0,
 7,
 14,
 17,
 0,
 0,
 3,
 16,
 0,
 0,
 0,
 13,
 6,
 7,
 0,
 0,
 20,
 13,
 0,
 0,
 0,
 0,
 0,
 7,
 0,
 0,
 16,
 0,
 0,
 0,
 0,
 7,
 0,
 3,
 0,
 13,
 6,
 0,
 22,
 6,
 13,
 0,
 0,
 10,
 3,
 0,
 0,
 15,
 0,
 0,
 0,
 0,
 0,
 2,
 16,
 0,
 0,
 0,
 3,
 23,
 0,
 19,
 0,
 0,
 11,
 25,
 25,
 0,
 6,
 0,
 0,
 12,
 0,
 0,
 25,
 25,
 13,
 15,
 0,
 12,
 11,
 2,
 0,
 6,
 14,
 6,
 0,
 0,
 25,
 13,
 0,
 19,
 5,
 25,
 0,
 12,
 0,
 0,
 7,
 0,
 0,
 0,
 12,
 16,
 16,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 13,
 0,
 20,
 6,
 3,
 0,
 0,
 0,
 0,
 0,
 25,
 7,
 0,
 12,
 0,
 13,
 10,
 14,
 2,
 22,
 0,
 0,
 0,
 5,
 11,
 0,
 4,
 0,
 0,
 0,
 0,
 0,
 25,
 0,
 0,
 20,
 0,
 0,
 10,
 0,
 6,
 13,
 3,
 14,
 3,
 12,
 0,
 25,
 0,
 0,
 12,
 16,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 10,
 5,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 25,
 0,
 0,
 0,
 23,
 0,
 16,
 0,
 0,
 0,
 0,
 3,
 7,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 20,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 20,
 0,
 25,
 0,
 0,
 0,
 6,
 8,
 0,
 16,
 13,
 16,
 0,
 16,
 0,
 0,
 23,
 13,
 0,
 0,
 14,
 0,
 3,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 4,
 20,
 0,
 0,
 22,
 0,
 4,
 7,
 0,
 0,
 0,
 22,
 12,
 0,
 0,
 0,
 15,
 0,
 0,
 7,
 3,
 0,
 4,
 0,
 0,
 0,
 7,
 14,
 3,
 15,
 0,
 25,
 0,
 0,
 0,
 0,
 0,
 0,
 6,
 0,
 0,
 6,
 17,
 0,
 13,
 0,
 0,
 0,
 0,
 5,
 6,
 0,
 0,
 0,
 0,
 14,
 0,
 4,
 0,
 0,
 7,
 20,
 0,
 7,
 14,
 4,
 3,
 13,
 0,
 0,
 7,
 0,
 13,
 6,
 16,
 7,
 0,
 16,
 0,
 6,
 0,
 6,
 0,
 0,
 13,
 0,
 0,
 0,
 0,
 15,
 14,
 11,
 25,
 0,
 0,
 0,
 0,
 22,
 0,
 0,
 0,
 3,
 7,
 20,
 0,
 0,
 3,
 0,
 15,
 0,
 13,
 0,
 0,
 0,
 23,
 0,
 0,
 2,
 0,
 0,
 17,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 16,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 14,
 0,
 0,
 14,
 0,
 1,
 0,
 0,
 4,
 0,
 0,
 25,
 0,
 0,
 0,
 16,
 13,
 7,
 5,
 0,
 0,
 23,
 0,
 5,
 0,
 0,
 23,
 0,
 0,
 0,
 25,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 20,
 0,
 16,
 0,
 0,
 0,
 0,
 15,
 0,
 13,
 25,
 7,
 6,
 0,
 0,
 6,
 0,
 0,
 5,
 0,
 0,
 0,
 5,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 7,
 7,
 14,
 0,
 14,
 0,
 16,
 0,
 0,
 0,
 0,
 0,
 4,
 0,
 24,
 0,
 0,
 6,
 0,
 7,
 0,
 3,
 7,
 0,
 3,
 0,
 0,
 15,
 0,
 16,
 0,
 3,
 13,
 7,
 24,
 0,
 0,
 0,
 0,
 24,
 0,
 22,
 1,
 0,
 16,
 0,
 4,
 5,
 0,
 0,
 0,
 25,
 0,
 10,
 0,
 0,
 0,
 0,
 0,
 7,
 0,
 0,
 3,
 25,
 0,
 7,
 0,
 0,
 9,
 0,
 0,
 4,
 13,
 16,
 0,
 0,
 0,
 9,
 0,
 0,
 0,
 25,
 0,
 6,
 0,
 16,
 0,
 0,
 0,
 17,
 7,
 0,
 5,
 7,
 0,
 0,
 5,
 6,
 0,
 0,
 6,
 0,
 0,
 0,
 0,
 5,
 0,
 12,
 0,
 4,
 7,
 0,
 7,
 10,
 7,
 0,
 0,
 4,
 16,
 24,
 0,
 0,
 0,
 16,
 3,
 1,
 0,
 20,
 3,
 20,
 0,
 13,
 25,
 23,
 4,
 0,
 13,
 3,
 0,
 17,
 0,
 7,
 0,
 3,
 4,
 0,
 7,
 6,
 0,
 0,
 0,
 13,
 0,
 0,
 0,
 0,
 0,
 20,
 0,
 0,
 0,
 13,
 0,
 13,
 6,
 22,
 0,
 0,
 0,
 0,
 13,
 0,
 0,
 22,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 16,
 0,
 0,
 17,
 0,
 0,
 6,
 25,
 20,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 5,
 0,
 0,
 7,
 0,
 0,
 16,
 13,
 14,
 16,
 0,
 23,
 0,
 0,
 0,
 3,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 2,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 10,
 6,
 0,
 0,
 2,
 0,
 9,
 0,
 0,
 5,
 0,
 2,
 6,
 13,
 0,
 0,
 6,
 0,
 0,
 0,
 3,
 0,
 0,
 0,
 0,
 0,
 0,
 5,
 0,
 5,
 0,
 0,
 2,
 0,
 0,
 24,
 3,
 0,
 0,
 0,
 0,
 13,
 0,
 17,
 0,
 0,
 5,
 0,
 0,
 -1,
 0,
 9,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 5,
 0,
 2,
 0,
 0,
 2,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 6,
 15,
 0,
 0,
 0,
 0,
 7,
 0,
 6,
 0,
 0,
 15,
 0,
 10,
 0,
 0,
 0,
 0,
 0,
 0,
 3,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 6,
 0,
 0,
 0,
 0,
 0,
 8,
 0,
 0,
 5,
 0,
 0,
 0,
 0,
 0,
 6,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 2,
 0,
 3,
 2,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 2,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 3,
 0,
 0,
 0,
 10,
 0,
 0,
 0,
 5,
 0,
 0,
 0,
 0,
 0,
 ...]

In [46]:
cor = Y33.count(0)
cor

10142

In [47]:
Accuracy = (cor/Test.shape[0])*100
Accuracy

68.52702702702703